### ISSUE TITLE
No IntersectionObserver instance found for element. Is it still mounted in the DOM?

### ISSUE THREAD

**Issue by jpolitowski** [thebuilder/react-intersection-observer#241] opened 2019-06-13 20:48 UTC
I'm having a bit of trouble writing a test. I'm getting this error:

> No IntersectionObserver instance found for element. Is it still mounted in the DOM?

```
import React from 'react';
import { shallow, mount } from 'enzyme';
import { mockIsIntersecting } from 'react-intersection-observer/test-utils';
import FeaturedRow from './index';

  it('Animates when in view', () => {
    const wrapper = mount(<FeaturedRow />);
    mockIsIntersecting(wrapper, true);

    expect(
      wrapper
        .find('div')
        .at(0)
        .prop('style'),
    ).toBe('transform: matrix(1, 0, 0, 1, 0, 0);');
  });
});

```
Thank you so much for this great plugin.

**Comment by thebuilder** [comment] 2019-06-13 21:10
I think it might be because your using Enzyme. I haven't tried it, so it might work just fine. 

But, you are passing the Enzyme wrapper to the test. It should be an actual DOM element.

**Comment by jpolitowski** [comment] 2019-06-13 21:12
Thank you so much for the fast reply! I really appreciate it.

When I log it out wrapper, it does appear to be an actual DOM element. I'll keep looking into it. 

Cheers

**Comment by thebuilder** [comment] 2019-06-13 22:01
You could use `mockAllIsIntersecting(true)` instead.

**Comment by robwierzbowski** [comment] 2019-06-14 14:39
@jpolitowsk Did you get this working with Enzyme? If so, could you post an example?

I'm not seeing the enzyme wrapper changing when I call `mockAllIsIntersecting(true)`.

**Comment by robwierzbowski** [comment] 2019-06-14 14:40
@jpolitowski  Did you get this working with Enzyme? If so, could you post an example?

I'm not seeing the enzyme wrapper changing when I call `mockAllIsIntersecting(true)`.

**Comment by jpolitowski** [comment] 2019-06-14 14:44
I did not see any change either. Thanks for following up!

**Comment by robwierzbowski** [comment] 2019-06-14 15:04
@thebuilder Could we re-open this issue as "test utils don't work with enzyme"?

**Comment by robwierzbowski** [comment] 2019-06-14 15:08
Ideally, this reduced test case would work for me: 

```
const ProgressiveLoader = ({ src }) => {
  const [ref, inView] = useInView({
    rootMargin: '0px 0px 200px 0px',
    triggerOnce: true,
  });

  return <img ref={ref} src={inView ? src : ''} />;
};


it('renders offscreen images when in view', () => {
      const wrapper = shallow(
        <ProgressiveLoader src={mockData.src} />,
      );

      mockAllIsIntersecting(true);

      expect(wrapper).toMatchSnapshot();
    });
```

**Comment by thebuilder** [comment] 2019-06-14 15:10
Can you recreate this in a CodeSandbox?

I suspect the wrapper itself might not update. Could you try logging the `inView` status? Maybe with `onChange`.

**Comment by robwierzbowski** [comment] 2019-06-14 15:11
Sure! I tried `wrapper.update()` and some `setImmediate` hacks, but no luck.

**Comment by robwierzbowski** [comment] 2019-06-14 18:21
OK, getting closer. 

This tweet from Dan Abramov talks about the known issue with shallow and updating state, and some more good info about React hooks:

![image](https://user-images.githubusercontent.com/925735/59524479-04547200-8ea2-11e9-9e96-98229cebf748.png)
https://twitter.com/dan_abramov/status/1103271660461924356?lang=en

After poking through Enzyme and React issues it seems like `shallow` does not currently update state with hooks. The problem is with state hooks in general, not this implementation in particular. `mount` does, if you run `.update` on your wrapper:

```
import React from 'react';
import { mount } from 'enzyme';

const ProgressiveLoader = ({ src }) => {
  const [ref, inView] = useInView({
    rootMargin: '0px 0px 200px 0px',
    triggerOnce: true,
  });

  return <img ref={ref} src={inView ? src : ''} />;
};


it('renders offscreen images when in view', () => {
  const wrapper = mount(<ProgressiveLoader src='/foo.jpg' />);

  mockAllIsIntersecting(true);

  wrapper.update();

  // Running snapshots on mounted instances is not usually a good idea
  expect(wrapper).toMatchSnapshot();  // Works!
});
```

React and Enzyme contributors know about this issue and are working on fixing it. I think we can close this and just work around it until the fixes are released by the React and Enzyme teams.

**Comment by thebuilder** [comment] 2019-06-16 09:50
Otherwise I'd highly recommend trying https://github.com/testing-library/react-testing-library

**Closed by thebuilder** 2019-06-16 09:50 UTC
